server:
  port: 8082

spring:
  application:
    name: single-consumer

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://dev:wangdong1995@localhost:8080/consul
