server:
  port: 8081

spring:
  application:
    name: single-provider

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://dev:wangdong1995@localhost:8080/consul